//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B211200005_CanberkSAKA
{
    using System;
    using System.Collections.Generic;
    
    public partial class KitapAciklamalari
    {
        public int AciklamaID { get; set; }
        public Nullable<int> KitapID { get; set; }
        public string Aciklama { get; set; }
    
        public virtual Kitaplar Kitaplar { get; set; }
    }
}
