//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B211200005_CanberkSAKA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitaplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kitaplar()
        {
            this.KitapAciklamalari = new HashSet<KitapAciklamalari>();
            this.KitapYazarIliskisi = new HashSet<KitapYazarIliskisi>();
            this.KitapYildizlari = new HashSet<KitapYildizlari>();
            this.SiparisDetaylari = new HashSet<SiparisDetaylari>();
        }
    
        public int KitapID { get; set; }
        public string KitapAdi { get; set; }
        public Nullable<int> YazarID { get; set; }
        public Nullable<int> KategoriID { get; set; }
        public Nullable<int> TurID { get; set; }
        public Nullable<int> YayineviID { get; set; }
        public Nullable<int> YildizID { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<int> StokMiktari { get; set; }
        public string KitapResim { get; set; }
        public Nullable<int> AciklamaID { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KitapAciklamalari> KitapAciklamalari { get; set; }
        public virtual Tur Tur { get; set; }
        public virtual Yayinevleri Yayinevleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KitapYazarIliskisi> KitapYazarIliskisi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KitapYildizlari> KitapYildizlari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisDetaylari> SiparisDetaylari { get; set; }
        public virtual Yazarlar Yazarlar { get; set; }
    }
}
